enum ActionTypeKeys {
  ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS',
  DELETE_TODO_SUCCESS = 'DELETE_TODO',
  TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS',
  UPDATE_FILTER = 'UPDATE_FILTER',
  LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS',
  UPDATE_TODOS_LOADING = 'UPDATE_TODOS_LOADING'
}

export default ActionTypeKeys;
