enum ActionTypeKeys {
  ADD_TODO = 'ADD_TODO',
  ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS',
  DELETE_TODO = 'DELETE_TODO',
  DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS',
  TOGGLE_TODO = 'TOGGLE_TODO',
  TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS',  
  FETCH_TODOS = 'FETCH_TODOS',
  FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS',
  UPDATE_FILTER = 'UPDATE_FILTER',  
  UPDATE_TODOS_LOADING = 'UPDATE_TODOS_LOADING'
}

export default ActionTypeKeys;
