enum ActionTypeKeys {
  ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS',
  DELETE_TODO = 'DELETE_TODO',
  TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS',
  UPDATE_FILTER = 'UPDATE_FILTER',
  LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS'
}

export default ActionTypeKeys;
